export const FETCH_ACTIVITY_REQUEST = "activity/FETCH_ACTIVITY_REQUEST";
export const FETCH_ACTIVITY_SUCCESS = "activity/FETCH_ACTIVITY_SUCCESS";
export const FETCH_ACTIVITY_FAILURE = "activity/FETCH_ACTIVITY_FAILURE";
