export const FETCH_PROJECT_TASKS_REQUEST = "tasks/FETCH_PROJECT_TASKS_REQUEST";
export const FETCH_PROJECT_TASKS_SUCCESS = "tasks/FETCH_PROJECT_TASKS_SUCCESS";
export const FETCH_PROJECT_TASKS_FAILURE = "tasks/FETCH_PROJECT_TASKS_FAILURE";

export const FETCH_MY_TASKS_REQUEST = "tasks/FETCH_MY_TASKS_REQUEST";
export const FETCH_MY_TASKS_SUCCESS = "tasks/FETCH_MY_TASKS_SUCCESS";
export const FETCH_MY_TASKS_FAILURE = "tasks/FETCH_MY_TASKS_FAILURE";

export const CREATE_TASK_REQUEST = "tasks/CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "tasks/CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "tasks/CREATE_TASK_FAILURE";

export const UPDATE_TASK_REQUEST = "tasks/UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "tasks/UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "tasks/UPDATE_TASK_FAILURE";

export const ADD_SUBTASK_REQUEST = "tasks/ADD_SUBTASK_REQUEST";
export const ADD_SUBTASK_SUCCESS = "tasks/ADD_SUBTASK_SUCCESS";
export const ADD_SUBTASK_FAILURE = "tasks/ADD_SUBTASK_FAILURE";

export const UPDATE_SUBTASK_REQUEST = "tasks/UPDATE_SUBTASK_REQUEST";
export const UPDATE_SUBTASK_SUCCESS = "tasks/UPDATE_SUBTASK_SUCCESS";
export const UPDATE_SUBTASK_FAILURE = "tasks/UPDATE_SUBTASK_FAILURE";

export const DELETE_SUBTASK_REQUEST = "tasks/DELETE_SUBTASK_REQUEST";
export const DELETE_SUBTASK_SUCCESS = "tasks/DELETE_SUBTASK_SUCCESS";
export const DELETE_SUBTASK_FAILURE = "tasks/DELETE_SUBTASK_FAILURE";

export const ADD_COMMENT_REQUEST = "tasks/ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "tasks/ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "tasks/ADD_COMMENT_FAILURE";

export const FETCH_TASK_BY_CODE_REQUEST = "tasks/FETCH_TASK_BY_CODE_REQUEST";
export const FETCH_TASK_BY_CODE_SUCCESS = "tasks/FETCH_TASK_BY_CODE_SUCCESS";
export const FETCH_TASK_BY_CODE_FAILURE = "tasks/FETCH_TASK_BY_CODE_FAILURE";

export const DELETE_TASK_REQUEST = "tasks/DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "tasks/DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "tasks/DELETE_TASK_FAILURE";

export const OPEN_CREATE_TASK_MODAL = "tasks/OPEN_CREATE_TASK_MODAL";
export const CLOSE_CREATE_TASK_MODAL = "tasks/CLOSE_CREATE_TASK_MODAL";
