export const FETCH_WEBHOOKS_REQUEST = "webhooks/FETCH_WEBHOOKS_REQUEST";
export const FETCH_WEBHOOKS_SUCCESS = "webhooks/FETCH_WEBHOOKS_SUCCESS";
export const FETCH_WEBHOOKS_FAILURE = "webhooks/FETCH_WEBHOOKS_FAILURE";

export const CREATE_WEBHOOK_REQUEST = "webhooks/CREATE_WEBHOOK_REQUEST";
export const CREATE_WEBHOOK_SUCCESS = "webhooks/CREATE_WEBHOOK_SUCCESS";
export const CREATE_WEBHOOK_FAILURE = "webhooks/CREATE_WEBHOOK_FAILURE";

export const DELETE_WEBHOOK_REQUEST = "webhooks/DELETE_WEBHOOK_REQUEST";
export const DELETE_WEBHOOK_SUCCESS = "webhooks/DELETE_WEBHOOK_SUCCESS";
export const DELETE_WEBHOOK_FAILURE = "webhooks/DELETE_WEBHOOK_FAILURE";

export const TEST_WEBHOOK_REQUEST = "webhooks/TEST_WEBHOOK_REQUEST";
export const TEST_WEBHOOK_SUCCESS = "webhooks/TEST_WEBHOOK_SUCCESS";
export const TEST_WEBHOOK_FAILURE = "webhooks/TEST_WEBHOOK_FAILURE";

export const OPEN_CREATE_WEBHOOK_MODAL = "webhooks/OPEN_CREATE_WEBHOOK_MODAL";
export const CLOSE_CREATE_WEBHOOK_MODAL = "webhooks/CLOSE_CREATE_WEBHOOK_MODAL";
