export const FETCH_INTEGRATIONS_REQUEST = "integrations/FETCH_INTEGRATIONS_REQUEST";
export const FETCH_INTEGRATIONS_SUCCESS = "integrations/FETCH_INTEGRATIONS_SUCCESS";
export const FETCH_INTEGRATIONS_FAILURE = "integrations/FETCH_INTEGRATIONS_FAILURE";

export const CONNECT_INTEGRATION_REQUEST = "integrations/CONNECT_INTEGRATION_REQUEST";
export const CONNECT_INTEGRATION_SUCCESS = "integrations/CONNECT_INTEGRATION_SUCCESS";
export const CONNECT_INTEGRATION_FAILURE = "integrations/CONNECT_INTEGRATION_FAILURE";

export const DISCONNECT_INTEGRATION_REQUEST = "integrations/DISCONNECT_INTEGRATION_REQUEST";
export const DISCONNECT_INTEGRATION_SUCCESS = "integrations/DISCONNECT_INTEGRATION_SUCCESS";
export const DISCONNECT_INTEGRATION_FAILURE = "integrations/DISCONNECT_INTEGRATION_FAILURE";
