export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "auth/LOGIN_FAILURE";

export const REGISTER_REQUEST = "auth/REGISTER_REQUEST";
export const REGISTER_SUCCESS = "auth/REGISTER_SUCCESS";
export const REGISTER_FAILURE = "auth/REGISTER_FAILURE";

export const REGISTER_VIA_INVITATION_REQUEST = "auth/REGISTER_VIA_INVITATION_REQUEST";
export const REGISTER_VIA_INVITATION_SUCCESS = "auth/REGISTER_VIA_INVITATION_SUCCESS";
export const REGISTER_VIA_INVITATION_FAILURE = "auth/REGISTER_VIA_INVITATION_FAILURE";

export const RESTORE_SESSION_REQUEST = "auth/RESTORE_SESSION_REQUEST";
export const RESTORE_SESSION_SUCCESS = "auth/RESTORE_SESSION_SUCCESS";
export const RESTORE_SESSION_FAILURE = "auth/RESTORE_SESSION_FAILURE";

export const LOGOUT = "auth/LOGOUT";

export const UPLOAD_AVATAR_REQUEST = "auth/UPLOAD_AVATAR_REQUEST";
export const UPLOAD_AVATAR_SUCCESS = "auth/UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAILURE = "auth/UPLOAD_AVATAR_FAILURE";

export const REMOVE_AVATAR_REQUEST = "auth/REMOVE_AVATAR_REQUEST";
export const REMOVE_AVATAR_SUCCESS = "auth/REMOVE_AVATAR_SUCCESS";
export const REMOVE_AVATAR_FAILURE = "auth/REMOVE_AVATAR_FAILURE";
