export const FETCH_API_KEYS_REQUEST = "apiKeys/FETCH_API_KEYS_REQUEST";
export const FETCH_API_KEYS_SUCCESS = "apiKeys/FETCH_API_KEYS_SUCCESS";
export const FETCH_API_KEYS_FAILURE = "apiKeys/FETCH_API_KEYS_FAILURE";

export const CREATE_API_KEY_REQUEST = "apiKeys/CREATE_API_KEY_REQUEST";
export const CREATE_API_KEY_SUCCESS = "apiKeys/CREATE_API_KEY_SUCCESS";
export const CREATE_API_KEY_FAILURE = "apiKeys/CREATE_API_KEY_FAILURE";

export const REVOKE_API_KEY_REQUEST = "apiKeys/REVOKE_API_KEY_REQUEST";
export const REVOKE_API_KEY_SUCCESS = "apiKeys/REVOKE_API_KEY_SUCCESS";
export const REVOKE_API_KEY_FAILURE = "apiKeys/REVOKE_API_KEY_FAILURE";

export const OPEN_CREATE_API_KEY_MODAL = "apiKeys/OPEN_CREATE_API_KEY_MODAL";
export const CLOSE_CREATE_API_KEY_MODAL = "apiKeys/CLOSE_CREATE_API_KEY_MODAL";
