export const FETCH_OVERVIEW_REQUEST = "analytics/FETCH_OVERVIEW_REQUEST";
export const FETCH_OVERVIEW_SUCCESS = "analytics/FETCH_OVERVIEW_SUCCESS";
export const FETCH_OVERVIEW_FAILURE = "analytics/FETCH_OVERVIEW_FAILURE";

export const FETCH_TEAM_PERFORMANCE_REQUEST = "analytics/FETCH_TEAM_PERFORMANCE_REQUEST";
export const FETCH_TEAM_PERFORMANCE_SUCCESS = "analytics/FETCH_TEAM_PERFORMANCE_SUCCESS";
export const FETCH_TEAM_PERFORMANCE_FAILURE = "analytics/FETCH_TEAM_PERFORMANCE_FAILURE";
