export const FETCH_PLANS_REQUEST = "billing/FETCH_PLANS_REQUEST";
export const FETCH_PLANS_SUCCESS = "billing/FETCH_PLANS_SUCCESS";
export const FETCH_PLANS_FAILURE = "billing/FETCH_PLANS_FAILURE";

export const FETCH_SUBSCRIPTION_REQUEST = "billing/FETCH_SUBSCRIPTION_REQUEST";
export const FETCH_SUBSCRIPTION_SUCCESS = "billing/FETCH_SUBSCRIPTION_SUCCESS";
export const FETCH_SUBSCRIPTION_FAILURE = "billing/FETCH_SUBSCRIPTION_FAILURE";

export const CREATE_CHECKOUT_REQUEST = "billing/CREATE_CHECKOUT_REQUEST";
export const CREATE_CHECKOUT_SUCCESS = "billing/CREATE_CHECKOUT_SUCCESS";
export const CREATE_CHECKOUT_FAILURE = "billing/CREATE_CHECKOUT_FAILURE";
export const CLEAR_CHECKOUT_SESSION = "billing/CLEAR_CHECKOUT_SESSION";

export const VERIFY_PAYMENT_REQUEST = "billing/VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "billing/VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAILURE = "billing/VERIFY_PAYMENT_FAILURE";

export const CANCEL_SUBSCRIPTION_REQUEST = "billing/CANCEL_SUBSCRIPTION_REQUEST";
export const CANCEL_SUBSCRIPTION_SUCCESS = "billing/CANCEL_SUBSCRIPTION_SUCCESS";
export const CANCEL_SUBSCRIPTION_FAILURE = "billing/CANCEL_SUBSCRIPTION_FAILURE";
